remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
title: Asmita Regmi
description: Data Analyst with expertise in building dashboards, ETL pipelines, and analytics solutions that drive business decisions. Proficient in SQL, Power BI, Python, and AWS. Experienced in transforming raw data into actionable insights through KPI reporting, data modeling, and cross-functional collaboration.
